markets:
- huobi
- okex
- binance

symbols:
#usdt:btc:eth:eos约4:2:1:1
- btc_usdt
- eth_usdt
- eos_usdt
#以下两个量很少
- eos_eth
- eos_btc
#- xrp_usdt
#- xrp_btc
#- xrp_eth

margins: #差价乘数
- 0.004

delays: #按照毫秒计算时间差
- 3000