markets:
#- huobi
#- okex
#- binance

symbols:
- btc_usdt
- eth_usdt
- eos_usdt
- eos_btc
- eth_btc
- eos_eth

margins: #差价乘数
- 0.0015

discountRate: 0.8

delays: #按照毫秒计算时间差
- 3000
env: aws
dbconnection: host=simonisgood.cfxtvaff0nlc.ap-northeast-1.rds.amazonaws.com port=54322 user=crook dbname=mydb password=zaq12WSX sslmode=disable
#env: silicon
#dbconnection: host=172.20.48.174 port=5432 user=crook dbname=mydb password=zaq12WSX sslmode=disable
