functions:
#- carry
#- balanceturtle
- arbitrary

bnbmin: 2
bnbbuy: 2

orderwait: 10000
delay: 6000 #按照毫秒计算时间差
channelslot: 200000 #按照毫秒计算的检查时间间隔
channels: 1
minusdt: 15
maxusdt: 1500
inchina: 0
deduction: 0.8

#env: local
#dbconnection: host=10.10.102.65 port=5432 user=odoo dbname=odoo password=123456 sslmode=disable
env: simon
dbconnection: host=simonisgood.cfxtvaff0nlc.ap-northeast-1.rds.amazonaws.com port=54322 user=crook dbname=test password=zaq12WSX sslmode=disable
#dbconnection: host=simonisgood.cfxtvaff0nlc.ap-northeast-1.rds.amazonaws.com port=54322 user=crook dbname=jack password=zaq12WSX sslmode=disable
#env: ace
#dbconnection: host=mydb.ckqil47vjyah.ap-northeast-1.rds.amazonaws.com port=5432 user=ace dbname=ace password=zaq12WSX sslmode=disable
#env: andrew
#dbconnection: host=mydb.clhbtnpqdvfn.us-east-2.rds.amazonaws.com port=5432 user=crook dbname=mydb password=zaq12WSX sslmode=disable
#dbconnection: host=mydb.clhbtnpqdvfn.us-east-2.rds.amazonaws.com port=5432 user=crook dbname=bitmex password=zaq12WSX sslmode=disable
#sammi huobi
#huobikey: 003fe1c2-1a5a12e1-73668e50-6773e
#huobisecret: 05d114f3-6f455bf3-a640f2c4-06050
huobikey: f5be33c8-e44026c8-4db512d3-908b3
huobisecret: 1826ba5a-022a7442-07a876f8-1075e
#sammi okex
#okexkey: 0b9a5af6-9e8f-47df-a0c6-5bb12d2431fa
#okexsecret: 3A3B33621B46EDA22AC5F08C244DBC13
#simon okex
okexkey: f8b9e6ac-dbd6-469e-9b10-4c1efc9d8d4c
okexsecret: 66786EDBC5F3230B7943DB520F86B492
#sammi binance
#binancekey: v5Z6FuiPMmBxFtUjWWrEIkD8RCjyL8Q136YoRVkJWRYfrdIQuYTfDqprCrE0FK1S
#binancesecret: 2QdNzj7NSlejGZWnhBES1MWWHWPA5ciw7AxukXB8q4dAO95u5kUwpBVGRjgEuL3L
#jack binance
binancekey: yAIAfvnOXnAfBD8jQfDe5AozVcbcTHCWADGTVWvk21KoKLtkcui96UCEiI0Ii3ix
binancesecret: mc7b0yTTGKU4sSnaP2lagYHUJTLNyQ7LX5spGZzEnjYHdhdfhHauxgzmkimjQ1cs
#ace fcoin
fcoinkey: 7c26be189ddc4e59aeb6021cfbfc3415
fcoinsecret: 54342819cbe148859f8d5ebdf384e607
#52.192.134.3,13.209.7.121,13.231.235.25,18.191.71.98
coinbigkey: 1E22104822C70BB607F159BAB6464C8E
coinbigsecret: 57F20C33AEB2F29171B77239EDBBC102
#yjsx_52.192.134.3,13.209.7.121,13.231.235.25,18.191.71.98
coinparkkey: 7315c14b57b5c0818dc48d9635c4342cc0ac4295
coinparksecret: 04943d9ed1735624bca2f3a88a216866b039b0ec
#bitmex test
#bitmexkey: pS4bU4i2fUlEpdZjGzcjP83h
#bitmexsecret: yLl0t87-dSbwu_R4mLLIVkNRlI3d7Kr2a9ZgtRDUjbm07GQm
#bitmex
bitmexkey: Esp86jOtjFZH4Gprd_cdk4pE
bitmexsecret: XC-m2-XMOJoX0FBfOcs60qkRprQcFDKMMfTyPpPBWOsKRccE