markets:
- huobi
- okex
- binance

symbols:
- btc_usdt
- eth_usdt
- eos_usdt
#以下两个量很少
- eos_eth
- eos_btc
- eth_btc
- xrp_usdt
- xrp_btc
- xrp_eth
#- bch-usdt
#- bch-btc
#- bch-eth

margins: #差价乘数
- 0.0015

delays: #按照毫秒计算时间差
- 3000
env: tencent
dbconnection: host=172.29.0.3 port=5432 user=winston dbname=coincarry password=User@123 sslmode=disable