markets:
#- huobi
#- okex
#- binance
- fcoin
#- coinpark
#- coinbig
#- btcdo

symbols:
#- ft_usdt
- eth_usdt
- eos_usdt
- eos_btc
- eth_btc
- eos_eth

deduction: 0.8

margins: #差价
- -0.00001
#- 0.0020
#- 0.0020
#- 0.0020
#- 0.0020
#- 0.0020

delays: #按照毫秒计算时间差
- 5000
basecarrycost: -0.00001
channelslot: 100000 #按照毫秒计算的检查时间间隔
channels: 1
minusdt: 15
maxusdt: 1500
inchina: 0
env: aws
dbconnection: host=simonisgood.cfxtvaff0nlc.ap-northeast-1.rds.amazonaws.com port=54322 user=crook dbname=one password=zaq12WSX sslmode=disable
#env: ace
#dbconnection: host=mydb.ckqil47vjyah.ap-northeast-1.rds.amazonaws.com port=5432 user=ace dbname=ace password=zaq12WSX sslmode=disable
#env: andrew
#dbconnection: host=mydb.clhbtnpqdvfn.us-east-2.rds.amazonaws.com port=5432 user=crook dbname=mydb password=zaq12WSX sslmode=disable

orderwait: 10000

#sammi huobi
huobikey: 003fe1c2-1a5a12e1-73668e50-6773e
huobisecret: 05d114f3-6f455bf3-a640f2c4-06050
#sammi okex
okexkey: bb709a25-4d5b-4d9a-83ba-17cb514506fc
okexsecret: 7D0E1B435964B96D72728215CB369CD7
#sammi binance
binancekey: v5Z6FuiPMmBxFtUjWWrEIkD8RCjyL8Q136YoRVkJWRYfrdIQuYTfDqprCrE0FK1S
binancesecret: 2QdNzj7NSlejGZWnhBES1MWWHWPA5ciw7AxukXB8q4dAO95u5kUwpBVGRjgEuL3L
#fcoin yjsx_
fcoinkey: b816373ea55049bfa586080952f8d89c
fcoinsecret: 35660fa142364a668eea7a3e32d27bcd
#116.233.200.203
coinbigkey: 932573681E0ED965D382C405DAD8DB98
coinbigsecret: 8F45F90B1A509AA987F32812E603C735
#yjsx_52.192.134.3,13.209.7.121,13.231.235.25,18.191.71.98
coinparkkey: f2e3679a4f7eddf786ae57d38b84a7992b6b8d86
coinparksecret: 8a6973ddfd9a5df5c4450ac61ab522293fe971e5
# all ip
btcdokey: AAAAAkNyFWrKUGQmFtUnYXe4TtxHNLlr
btcdosecret: GjCgP2TEQ2sppUhjeiv8