markets:
  huobi:
    btc: 0.3
    eth: 0.15
    eos: 0.25
    usdt: 0.3
  okex:
    btc: 0.3
    eth: 0.15
    eos: 0.25
    usdt: 0.3
  binance:
    btc: 0.3
    eth: 0.15
    eos: 0.25
    usdt: 0.3

symbols:
- btc_usdt
- eth_usdt
- eos_usdt
#以下两个量很少
- eos_eth
- eos_btc
#- xrp_usdt
#- xrp_btc
#- xrp_eth

margins: #差价乘数
- 0.002

delays: #按照毫秒计算时间差
- 3000